### ISSUE TITLE
add commits message standardization setting

### ISSUE THREAD

**Issue by brunosousadev** [lucas-eduardo/tarvos-express#1]
Required libs:
 

1. husky ;
2. @commitlint/cli;
3. commitizen.

If necessary I can help with the configuration.

**Comment by lucas-eduardo** [comment]
@brunosousadev Opa, tudo bem?

Se quiser estar contribuindo, fique a vontade. Só fazer as aberturas de PR e vou colocar você como contribuidor no projeto
